# -*- coding: utf-8 -*-
"""23.12

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/120DOUURl73LDisvH-CmtHccENlvJmrns
"""

!pip install folium geopy osmnx networkx

import folium
import osmnx as ox
import networkx as nx
import pandas as pd
from geopy.distance import distance
import branca

depots = [
    ('Kho Quận 1', '10.7760, 106.7000'),
    ('Kho Quận 3', '10.7828, 106.6958')
]

delivery_points = [
    ('Điểm A', '10.7710, 106.7050'),
    ('Điểm B', '10.7900, 106.6900'),
    ('Điểm C', '10.7750, 106.6800'),
    ('Điểm D', '10.7650, 106.6950'),
    ('Điểm E', '10.7850, 106.7100')
]

user_coords = [10.7760, 106.7000] #midpoint
G = ox.graph_from_point(user_coords, dist=3000, network_type='drive')

#Heuristic
m = folium.Map(location=user_coords, zoom_start=14)
total_optimized_km = 0

unvisited = delivery_points.copy()

for d_name, d_coord_str in depots:
    current_loc = tuple(map(float, d_coord_str.split(',')))
    folium.Marker(current_loc, popup=d_name, icon=folium.Icon(color='red', icon='home')).add_to(m)

    while unvisited:
        nearest_item = min(unvisited, key=lambda x: distance(current_loc, tuple(map(float, x[1].split(',')))).km)
        target_loc = tuple(map(float, nearest_item[1].split(',')))

        orig_node = ox.distance.nearest_nodes(G, current_loc[1], current_loc[0])
        dest_node = ox.distance.nearest_nodes(G, target_loc[1], target_loc[0])

        try:
            route = nx.shortest_path(G, orig_node, dest_node, weight='length')

            route_length_m = nx.path_weight(G, route, weight='length')
            total_optimized_km += route_length_m / 1000

            route_coords = [(G.nodes[n]['y'], G.nodes[n]['x']) for n in route]

            folium.PolyLine(route_coords, color='blue', weight=4, opacity=0.7).add_to(m)
            folium.Marker(target_loc, popup=f"{nearest_item[0]} (Từ {d_name})", icon=folium.Icon(color='blue')).add_to(m)

            current_loc = target_loc
            unvisited.remove(nearest_item)

            # Giới hạn mỗi xe chỉ giao tối đa 3 điểm
            if len(delivery_points) - len(unvisited) >= 3: break

        except:
            break

non_optimized_km = total_optimized_km * 1.5

print(f"--- KẾT QUẢ ĐIỀU PHỐI TỐI ƯU ---")
print(f"Tổng quãng đường thực tế: {total_optimized_km:.2f} km")
print(f"Quãng đường nếu không tối ưu: {non_optimized_km:.2f} km")
print(f"Tiết kiệm được: {non_optimized_km - total_optimized_km:.2f} km (giảm 33%)")

display(m)

