# -*- coding: utf-8 -*-
"""23.15

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IEqWQB98bJQ5JyayNrcsuvnSo3M3q_Wp
"""

!pip install folium geopy osmnx networkx

from geopy.geocoders import Nominatim
from geopy.distance import distance
import folium
import osmnx as ox
import networkx as nx

geolocator = Nominatim(user_agent="Taxi")

#nhập vị trí người đứng
a = input("Nhập vị trí người dùng: ")
location_a = geolocator.geocode(a)
print("Xác nhận vị trí người dùng là: ",location_a)
user_coords = (location_a.latitude, location_a.longitude)
m = folium.Map(location=user_coords, zoom_start=13)
folium.Marker(user_coords, popup="Vị trí hiện tại", tooltip='Click vào').add_to(m)

G = ox.graph_from_point(user_coords, dist=5000, network_type='drive')

cosoUEH = [
    ('Cơ sở A','10.7830881,106.6920879'),
    ('Cơ sở B','10.7610585,106.6657777'),
    ('Cơ sở C','10.7731605,106.6750231'),
    ('Cơ sở N','10.7060233,106.6375486')]

for name, coord in cosoUEH:
    dist = distance(user_coords, coord).km
    print(f'{name}: {dist:.2f} km từ vị trí đang đứng')
    coord = tuple(map(float, coord.split(',')))
    folium.Marker([coord[0],coord[1]], popup=name, tooltip='Click vào').add_to(m)


nearest = min(cosoUEH, key=lambda x: distance(user_coords, tuple(map(float, x[1].split(',')))).km)
print(f"Cơ sở gần nhất là: {nearest[0]} ({distance(user_coords, nearest[1]).km:.2f} km)")

coord_min = tuple(map(float, nearest[1].split(',')))
latlng_A = coord_min[0]
latlng_B = coord_min[1]
orig_node = ox.distance.nearest_nodes(G, latlng_B, latlng_A)
dest_node = ox.distance.nearest_nodes(G, user_coords[1], user_coords[0])
route = nx.shortest_path(G, orig_node, dest_node, weight='length')
route_coords = [(G.nodes[n]['y'], G.nodes[n]['x']) for n in route]
folium.PolyLine(locations=route_coords, color='green', weight=5, opacity=0.8).add_to(m)
display(m)