# -*- coding: utf-8 -*-
"""23.13

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t5GZrfUycg0MjmXNKWgktYI66nE8584R
"""

import folium
from folium import plugins
import branca

diem = [10.7760, 106.7000]
m = folium.Map(location=diem, zoom_start=13, tiles='CartoDB positron')

fg_stores = folium.FeatureGroup(name='Hệ thống cửa hàng').add_to(m)
fg_regions = folium.FeatureGroup(name='Khu vực').add_to(m)
fg_routes = folium.FeatureGroup(name='Tuyến đường vận chuyển').add_to(m)

folium.Marker([10.7760, 106.7000], popup='Kho Quận 1', icon=folium.Icon(color='red', icon='shopping-cart')).add_to(fg_stores)
folium.Marker([10.7828, 106.6958], popup='Cửa hàng Quận 3', icon=folium.Icon(color='red', icon='shopping-cart')).add_to(fg_stores)

folium.Circle(location=diem, radius=2000, color='green', fill=True, fill_opacity=0.2, popup='Vùng ưu tiên giao hàng').add_to(fg_regions)

route_sample = [[10.7760, 106.7000], [10.7800, 106.7050], [10.7828, 106.6958]]
folium.PolyLine(route_sample, color='blue', weight=5, opacity=0.6, tooltip='Tuyến xe tải số 01').add_to(fg_routes)

folium.LayerControl(collapsed=False).add_to(m)
m

