# -*- coding: utf-8 -*-
"""23.1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19BnDVoL-5GhkF2zpcin30SRJl-vrrrwh
"""

import folium
m = folium.Map(location=[10.7830881,106.6920879], zoom_start=13)
folium.Marker([10.7830881,106.6920879], popup="Cơ sở A UEH", tooltip='Click vào').add_to(m)
folium.Marker([10.7610585,106.6657777], popup="Cơ sở B UEH", tooltip='Click vào').add_to(m)
folium.Marker([10.7731605,106.6750231], popup="Cơ sở C UEH", tooltip='Click vào').add_to(m)
folium.Marker([10.7060233,106.6375486], popup="Cơ sở N UEH", tooltip='Click vào').add_to(m)
folium.Marker([10.7682541,106.7042225], popup="Bảo tàng CNCS HCM", tooltip='Click vào').add_to(m)
folium.Marker([10.7737239,106.7005553], popup="Bến tàu Bạch Đằng", tooltip='Click vào').add_to(m)
m

