# -*- coding: utf-8 -*-
"""23.2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19Eb-0s7eSQ5pXasyUMMvqkU7hJB6f5a4
"""

import folium
from geopy.geocoders import Nominatim
from geopy.distance import distance
from geopy.distance import geodesic

geolocator = Nominatim(user_agent="my_app")

c = input("Nhập vị trí người dùng: ")
d = geolocator.geocode(c)
user_coord = (d.latitude, d.longitude)
m = folium.Map(location=user_coord, zoom_start=13)
folium.Marker(user_coord, popup="Vị trí hiện tại", tooltip='Click vào').add_to(m)

locas = [
    ('Bến tàu Bạch Đằng','10.7752539,106.7046823'),
    ('Rex Hotel','10.7757164,106.6997468'),
    ('Ben Thanh Market','10.7757164,106.6997468'),
    ('Independence Palace','10.7736446,106.6954245'),
    ('War Remnants Museum','10.7754368,106.6906399'),
    ('Notre Dame Cathedral of Saigon','10.7803399,106.6930494')
]
for name, coord in locas:
  toado = geolocator.geocode(name)
  if toado is None:
    print(f"Không tìm thấy tọa độ của {name}")
  else:
    td = (toado.latitude, toado.longitude)
    dist = distance(user_coord, td).km
    print(f"Khoảng cách giữa {name} đến vị trí hiện tại là: {dist:.2f} km")
    folium.Marker(td, popup=name, tooltip='Click vào').add_to(m)
    folium.PolyLine([user_coord, td], color="blue").add_to(m)
m

