# -*- coding: utf-8 -*-
"""23.3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13qDP5wcGBJ3grajLoBUyPIFx6HVNXAJu
"""

import folium
from geopy.geocoders import Nominatim
from geopy.distance import distance
from geopy.distance import geodesic
from folium.plugins import HeatMap

geolocator = Nominatim(user_agent="my_app")

locas = [
    [10.7752539,106.7046823],
    [10.7757164,106.6997468],
    [10.7757164,106.6997468],
    [10.7736446,106.6954245],
    [10.7754368,106.6906399]]

m = folium.Map(location=[10.744632,106.626113], zoom_start=13)
folium.Marker([10.744632,106.626113], popup="Vị trí hiện tại", tooltip='Click vào').add_to(m)

HeatMap(locas).add_to(m)
m

