# -*- coding: utf-8 -*-
"""23.4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YlP1jmgaNUY74na87OnhcK4gSRlDHkgJ
"""

import geopandas as gpd
import pandas as pd
import folium

# 1. Đọc dữ liệu ranh giới hành chính (GeoJSON các tỉnh Việt Nam)
# URL cũ: "https://raw.githubusercontent.com/Vizzuality/growasia_impact_tool/master/data/Vietnam_Provinces.geojson"
url = "https://raw.githubusercontent.com/namtx/vietnam-geojson/master/provinces.geojson"
gdf = gpd.read_file(url)

# 2. Giả lập tập dữ liệu số (Ví dụ: Doanh thu theo tỉnh - đơn vị: tỷ đồng)
# Lưu ý: Tên tỉnh phải khớp với dữ liệu trong file GeoJSON
data = pd.DataFrame({
    'Province': ['Hồ Chí Minh', 'Hà Nội', 'Đà Nẵng', 'Cần Thơ', 'Hải Phòng', 'Bình Dương', 'Đồng Nai'],
    'Revenue': [5000, 4200, 2500, 1800, 2100, 3500, 3200]
})

# 3. Kết hợp dữ liệu (Merge)
# Trong file GeoJSON này, cột tên tỉnh thường là 'name'
# Chúng ta sẽ giữ lại cột hình học và gắn thêm dữ liệu doanh thu
merged = gdf.merge(data, left_on='name', right_on='Province', how='left')
merged['Revenue'] = merged['Revenue'].fillna(0) # Những tỉnh không có dữ liệu sẽ để bằng 0

# 4. Vẽ bản đồ Choropleth
m = folium.Map(location=[15.8, 108], zoom_start=5)

folium.Choropleth(
    geo_data=gdf,
    name="Doanh thu các tỉnh",
    data=data,
    columns=["Province", "Revenue"],
    key_on="feature.properties.name", # Đường dẫn đến tên tỉnh trong GeoJSON
    fill_color="YlOrRd", # Màu từ Vàng (thấp) đến Đỏ (cao)
    fill_opacity=0.7,
    line_opacity=0.2,
    legend_name="Mức doanh thu (Tỷ VNĐ)"
).add_to(m)

m

