# -*- coding: utf-8 -*-
"""23.5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NElBm30fKgD6pxY8dG2m5-cezhYPFQI7
"""

import folium
from geopy.geocoders import Nominatim
from geopy.distance import distance
from geopy.distance import geodesic
from folium.plugins import HeatMap

csA = [10.7447083,106.5851689]
geolocator = Nominatim(user_agent="Bai_Tap_23.5")

locas = [
    [10.7767501,106.701425], #Bến tàu Bạch Đằng
    [10.7757164,106.6997468], #Museum of Ho Chi Minh City
    [10.7748759,106.6932157], #Independence Palace
    [10.7736446,106.6954245], #Nguyen Du Park Villas
    [10.7752883,106.6899919]] #Tao Dan Park

m = folium.Map(location=csA, zoom_start=13)
folium.Marker(location=csA, popup="Vị trí hiện tại", tooltip='Click vào').add_to(m)
folium.Circle([10.7767501,106.701425], radius=500, color='red', fill=True).add_to(m)
folium.Circle([10.7757164,106.6997468], radius=500, color='blue', fill=True).add_to(m)
folium.Circle([10.7748759,106.6932157], radius=500, color='green', fill=True).add_to(m)
folium.Circle([10.7736446,106.6954245], radius=500, color='yellow', fill=True).add_to(m)
folium.Circle([10.7752883,106.6899919], radius=500, color='gray', fill=True).add_to(m)
m

