# -*- coding: utf-8 -*-
"""23.6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kBr_4g8SGeRTWekikbFNetG5pchZkLfY
"""

!pip install folium geopy osmnx networkx

import folium
from geopy.geocoders import Nominatim
import osmnx as ox
import branca

geolocator = Nominatim(user_agent="Bai_Tap_23.6")
location_name = "Independence Palace"
location = geolocator.geocode(location_name)
user_coord = (location.latitude, location.longitude)

G = ox.graph_from_point(user_coord, dist=1000, network_type='drive')
stats = ox.basic_stats(G)

m = folium.Map(location=user_coord, zoom_start=15)

html = f"""
    <h1>Thông tin khu vực</h1>
    <p><b>Địa điểm:</b> Dinh Độc Lập</p>
        <b>Số nút giao: {stats['n']}
        <b>Số đoạn đường:</b> {stats['m']}
        <b>Chiều dài TB:</b> {stats['street_length_avg']:.2f} m
"""
iframe = branca.element.IFrame(html=html, width=250, height=180)
popup = folium.Popup(iframe, max_width=300)

folium.Marker(location=user_coord, popup=popup,tooltip="Click để xem").add_to(m)
m

