# -*- coding: utf-8 -*-
"""23.7

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hokk3KjHoPwlUFz3gLAZ91JgHg_awwBA
"""

!pip install folium geopy osmnx networkx

import osmnx as ox
import networkx as nx
from geopy.geocoders import Nominatim
import folium
import time

geolocator = Nominatim(user_agent="Bai_Tap_23.7")
area = "District 1, Ho Chi Minh City, Vietnam"
G = ox.graph_from_place(area, network_type='drive')

tenA = "Saigon Skydeck"
toadoA = geolocator.geocode(tenA)
toadoA = (toadoA.latitude, toadoA.longitude)
m = folium.Map(location=toadoA, zoom_start=15)
tenB = "Museum of Ho Chi Minh City"
toadoB = geolocator.geocode(tenB)
toadoB = (toadoB.latitude, toadoB.longitude)
folium.Marker(toadoA, popup="Điểm đi", icon=folium.Icon(color='green')).add_to(m)
folium.Marker(toadoB, popup="Điểm đến", icon=folium.Icon(color='red')).add_to(m)
orig_node = ox.distance.nearest_nodes(G, toadoA[1], toadoA[0])
dest_node = ox.distance.nearest_nodes(G, toadoB[1], toadoB[0])

#Dijkstra GPT
start_time = time.time()
route_dijkstra = nx.shortest_path(G, orig_node, dest_node, weight='length', method='dijkstra')
time_dijkstra = time.time() - start_time

#A* GPT
start_time = time.time()
route_astar = nx.astar_path(G, orig_node, dest_node, weight='length')
time_astar = time.time() - start_time

route_coords = [(G.nodes[n]['y'], G.nodes[n]['x']) for n in route_astar]
folium.PolyLine(route_coords, color='blue', weight=5, opacity=0.7, tooltip="Click vào đây").add_to(m)
m

